"""add_email_notification_prefereces

Revision ID: 015a176d4563
Revises: 86af70098c80
Create Date: 2026-01-29 08:46:58.403347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015a176d4563'
down_revision: Union[str, Sequence[str], None] = '86af70098c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_on_post_success', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True))
    op.add_column('users', sa.Column('email_on_post_failure', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True))
    op.add_column('users', sa.Column('email_weekly_analytics', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_weekly_analytics')
    op.drop_column('users', 'email_on_post_failure')
    op.drop_column('users', 'email_on_post_success')
    # ### end Alembic commands ###
