"""Added some missing fields to the social connections table

Revision ID: 0eef7e842d3e
Revises: 94660b15eb8a
Create Date: 2025-10-25 21:26:03.029713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0eef7e842d3e'
down_revision: Union[str, Sequence[str], None] = '94660b15eb8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'platform_specific_content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('social_connections', sa.Column('platform_avatar_url', sa.String(), nullable=True))
    op.add_column('social_connections', sa.Column('platform_username', sa.String(), nullable=True))
    op.add_column('social_connections', sa.Column('last_synced', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_connections', 'last_synced')
    op.drop_column('social_connections', 'platform_username')
    op.drop_column('social_connections', 'platform_avatar_url')
    op.alter_column('posts', 'platform_specific_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
