"""added_template_folder_autopopulates

Revision ID: 27ddf40f7870
Revises: 4d87f7c0989a
Create Date: 2026-01-10 22:50:48.796472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ddf40f7870'
down_revision: Union[str, Sequence[str], None] = '4d87f7c0989a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
