"""stopped_using_enums

Revision ID: 3e5b60f884bc
Revises: e78559e4b30c
Create Date: 2026-01-11 14:39:28.583973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e5b60f884bc'
down_revision: Union[str, Sequence[str], None] = 'e78559e4b30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_analytics_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('total_posts', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_engagements', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_impressions', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('avg_engagement_rate', sa.Float(), server_default=sa.text('0.0'), nullable=True),
    sa.Column('platform_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', 'start_date', name='uq_user_period_start')
    )
    op.create_index(op.f('ix_user_analytics_summaries_id'), 'user_analytics_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_user_analytics_summaries_period'), 'user_analytics_summaries', ['period'], unique=False)
    op.create_index(op.f('ix_user_analytics_summaries_start_date'), 'user_analytics_summaries', ['start_date'], unique=False)
    op.create_index(op.f('ix_user_analytics_summaries_user_id'), 'user_analytics_summaries', ['user_id'], unique=False)
    op.create_table('post_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'platform', name='uq_post_platform')
    )
    op.create_index(op.f('ix_post_analytics_fetched_at'), 'post_analytics', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_post_analytics_id'), 'post_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_post_analytics_platform'), 'post_analytics', ['platform'], unique=False)
    op.create_index(op.f('ix_post_analytics_post_id'), 'post_analytics', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_results_post_id'), 'post_results', ['post_id'], unique=False)
    op.drop_constraint(op.f('post_results_post_id_fkey'), 'post_results', type_='foreignkey')
    op.create_foreign_key(None, 'post_results', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post_results', 'shares_count')
    op.drop_column('post_results', 'views_count')
    op.drop_column('post_results', 'likes_count')
    op.drop_column('post_results', 'comments_count')
    op.create_index(op.f('ix_post_templates_user_id'), 'post_templates', ['user_id'], unique=False)
    op.drop_constraint(op.f('post_templates_user_id_fkey'), 'post_templates', type_='foreignkey')
    op.drop_constraint(op.f('post_templates_folder_id_fkey'), 'post_templates', type_='foreignkey')
    op.create_foreign_key(None, 'post_templates', 'template_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'post_templates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_posts_scheduled_for'), 'posts', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.drop_constraint(op.f('posts_user_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_social_connections_platform'), 'social_connections', ['platform'], unique=False)
    op.create_index(op.f('ix_social_connections_user_id'), 'social_connections', ['user_id'], unique=False)
    op.drop_constraint(op.f('social_connections_user_id_fkey'), 'social_connections', type_='foreignkey')
    op.create_foreign_key(None, 'social_connections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.drop_constraint(op.f('subscriptions_user_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_template_analytics_template_id'), 'template_analytics', ['template_id'], unique=False)
    op.drop_constraint(op.f('template_analytics_template_id_fkey'), 'template_analytics', type_='foreignkey')
    op.drop_constraint(op.f('template_analytics_post_id_fkey'), 'template_analytics', type_='foreignkey')
    op.create_foreign_key(None, 'template_analytics', 'posts', ['post_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'template_analytics', 'post_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_template_folders_user_id'), 'template_folders', ['user_id'], unique=False)
    op.drop_constraint(op.f('template_folders_user_id_fkey'), 'template_folders', type_='foreignkey')
    op.create_foreign_key(None, 'template_folders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template_folders', type_='foreignkey')
    op.create_foreign_key(op.f('template_folders_user_id_fkey'), 'template_folders', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_template_folders_user_id'), table_name='template_folders')
    op.drop_constraint(None, 'template_analytics', type_='foreignkey')
    op.drop_constraint(None, 'template_analytics', type_='foreignkey')
    op.create_foreign_key(op.f('template_analytics_post_id_fkey'), 'template_analytics', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(op.f('template_analytics_template_id_fkey'), 'template_analytics', 'post_templates', ['template_id'], ['id'])
    op.drop_index(op.f('ix_template_analytics_template_id'), table_name='template_analytics')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_user_id_fkey'), 'subscriptions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_constraint(None, 'social_connections', type_='foreignkey')
    op.create_foreign_key(op.f('social_connections_user_id_fkey'), 'social_connections', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_social_connections_user_id'), table_name='social_connections')
    op.drop_index(op.f('ix_social_connections_platform'), table_name='social_connections')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_user_id_fkey'), 'posts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_scheduled_for'), table_name='posts')
    op.drop_constraint(None, 'post_templates', type_='foreignkey')
    op.drop_constraint(None, 'post_templates', type_='foreignkey')
    op.create_foreign_key(op.f('post_templates_folder_id_fkey'), 'post_templates', 'template_folders', ['folder_id'], ['id'])
    op.create_foreign_key(op.f('post_templates_user_id_fkey'), 'post_templates', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_post_templates_user_id'), table_name='post_templates')
    op.add_column('post_results', sa.Column('comments_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('post_results', sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('post_results', sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('post_results', sa.Column('shares_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post_results', type_='foreignkey')
    op.create_foreign_key(op.f('post_results_post_id_fkey'), 'post_results', 'posts', ['post_id'], ['id'])
    op.drop_index(op.f('ix_post_results_post_id'), table_name='post_results')
    op.drop_index(op.f('ix_post_analytics_post_id'), table_name='post_analytics')
    op.drop_index(op.f('ix_post_analytics_platform'), table_name='post_analytics')
    op.drop_index(op.f('ix_post_analytics_id'), table_name='post_analytics')
    op.drop_index(op.f('ix_post_analytics_fetched_at'), table_name='post_analytics')
    op.drop_table('post_analytics')
    op.drop_index(op.f('ix_user_analytics_summaries_user_id'), table_name='user_analytics_summaries')
    op.drop_index(op.f('ix_user_analytics_summaries_start_date'), table_name='user_analytics_summaries')
    op.drop_index(op.f('ix_user_analytics_summaries_period'), table_name='user_analytics_summaries')
    op.drop_index(op.f('ix_user_analytics_summaries_id'), table_name='user_analytics_summaries')
    op.drop_table('user_analytics_summaries')
    # ### end Alembic commands ###
