"""created_new_template_tables

Revision ID: 4d87f7c0989a
Revises: ae6a2f038468
Create Date: 2026-01-10 10:50:11.147539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d87f7c0989a'
down_revision: Union[str, Sequence[str], None] = 'ae6a2f038468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_folders_id'), 'template_folders', ['id'], unique=False)
    op.create_table('template_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['post_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_analytics_id'), 'template_analytics', ['id'], unique=False)
    op.add_column('post_templates', sa.Column('category', sa.String(), nullable=False))
    op.add_column('post_templates', sa.Column('content_template', sa.Text(), nullable=False))
    op.add_column('post_templates', sa.Column('variables', sa.JSON(), nullable=True))
    op.add_column('post_templates', sa.Column('platform_variations', sa.JSON(), nullable=True))
    op.add_column('post_templates', sa.Column('supported_platforms', sa.JSON(), nullable=False))
    op.add_column('post_templates', sa.Column('suggested_hashtags', sa.JSON(), nullable=True))
    op.add_column('post_templates', sa.Column('suggested_media_type', sa.String(), nullable=True))
    op.add_column('post_templates', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.add_column('post_templates', sa.Column('is_system', sa.Boolean(), nullable=True))
    op.add_column('post_templates', sa.Column('success_rate', sa.Integer(), nullable=True))
    op.add_column('post_templates', sa.Column('avg_engagement', sa.JSON(), nullable=True))
    op.add_column('post_templates', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('post_templates', sa.Column('color_scheme', sa.String(), nullable=True))
    op.add_column('post_templates', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('post_templates', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.alter_column('post_templates', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_post_templates_category'), 'post_templates', ['category'], unique=False)
    op.create_index(op.f('ix_post_templates_name'), 'post_templates', ['name'], unique=False)
    op.create_foreign_key(None, 'post_templates', 'template_folders', ['folder_id'], ['id'])
    op.drop_column('post_templates', 'platforms')
    op.drop_column('post_templates', 'default_hashtags')
    op.drop_column('post_templates', 'image_style')
    op.drop_column('post_templates', 'include_image')
    op.drop_column('post_templates', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_templates', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('post_templates', sa.Column('include_image', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('post_templates', sa.Column('image_style', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('post_templates', sa.Column('default_hashtags', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('post_templates', sa.Column('platforms', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post_templates', type_='foreignkey')
    op.drop_index(op.f('ix_post_templates_name'), table_name='post_templates')
    op.drop_index(op.f('ix_post_templates_category'), table_name='post_templates')
    op.alter_column('post_templates', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('post_templates', 'folder_id')
    op.drop_column('post_templates', 'icon')
    op.drop_column('post_templates', 'color_scheme')
    op.drop_column('post_templates', 'thumbnail_url')
    op.drop_column('post_templates', 'avg_engagement')
    op.drop_column('post_templates', 'success_rate')
    op.drop_column('post_templates', 'is_system')
    op.drop_column('post_templates', 'is_premium')
    op.drop_column('post_templates', 'suggested_media_type')
    op.drop_column('post_templates', 'suggested_hashtags')
    op.drop_column('post_templates', 'supported_platforms')
    op.drop_column('post_templates', 'platform_variations')
    op.drop_column('post_templates', 'variables')
    op.drop_column('post_templates', 'content_template')
    op.drop_column('post_templates', 'category')
    op.drop_index(op.f('ix_template_analytics_id'), table_name='template_analytics')
    op.drop_table('template_analytics')
    op.drop_index(op.f('ix_template_folders_id'), table_name='template_folders')
    op.drop_table('template_folders')
    # ### end Alembic commands ###
