"""Updated the post url to platform post url in the post result table

Revision ID: 674238eac5ea
Revises: dd4a15bb9eff
Create Date: 2025-12-30 10:05:34.543782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674238eac5ea'
down_revision: Union[str, Sequence[str], None] = 'dd4a15bb9eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_results', sa.Column('platform_post_url', sa.String(), nullable=True))
    op.drop_column('post_results', 'post_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_results', sa.Column('post_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('post_results', 'platform_post_url')
    # ### end Alembic commands ###
