"""Updated the post analytics table 

Revision ID: 6d30c018668e
Revises: 97e4afd9ea88
Create Date: 2026-01-14 09:08:56.987749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d30c018668e'
down_revision: Union[str, Sequence[str], None] = '97e4afd9ea88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_analytics', sa.Column('views', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('post_analytics', sa.Column('impressions', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('post_analytics', sa.Column('reach', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('post_analytics', sa.Column('likes', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('post_analytics', sa.Column('comments', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('post_analytics', sa.Column('shares', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('post_analytics', sa.Column('saves', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('post_analytics', sa.Column('clicks', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('post_analytics', sa.Column('platform_specific_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('post_analytics', sa.Column('engagement_rate', sa.Float(), server_default=sa.text('0.0'), nullable=True))
    op.alter_column('post_analytics', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('post_analytics', 'metrics')
    op.alter_column('post_templates', 'tone',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'engaging'::character varying"))
    op.alter_column('post_templates', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('post_templates', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('post_templates', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('post_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('post_templates', 'success_rate',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('post_templates', 'color_scheme',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'#3B82F6'::character varying"))
    op.alter_column('post_templates', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'sparkles'::character varying"))
    op.alter_column('post_templates', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('post_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('post_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('post_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('post_templates', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('post_templates', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'sparkles'::character varying"))
    op.alter_column('post_templates', 'color_scheme',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'#3B82F6'::character varying"))
    op.alter_column('post_templates', 'success_rate',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('post_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('post_templates', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('post_templates', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('post_templates', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('post_templates', 'tone',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'engaging'::character varying"))
    op.add_column('post_analytics', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('post_analytics', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('post_analytics', 'engagement_rate')
    op.drop_column('post_analytics', 'platform_specific_metrics')
    op.drop_column('post_analytics', 'clicks')
    op.drop_column('post_analytics', 'saves')
    op.drop_column('post_analytics', 'shares')
    op.drop_column('post_analytics', 'comments')
    op.drop_column('post_analytics', 'likes')
    op.drop_column('post_analytics', 'reach')
    op.drop_column('post_analytics', 'impressions')
    op.drop_column('post_analytics', 'views')
    # ### end Alembic commands ###
