"""added_auth_provider_last_login_method_user's_table

Revision ID: 86af70098c80
Revises: 6d30c018668e
Create Date: 2026-01-28 10:22:42.749828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86af70098c80'
down_revision: Union[str, Sequence[str], None] = '6d30c018668e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_login_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_method')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
