"""Added some facebook specific fields specifically for the facebook pages to have a connection with the facebook page and actually be able to integrate this smoothly

Revision ID: 89c1b0505e6e
Revises: 674238eac5ea
Create Date: 2026-01-02 09:04:27.389720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c1b0505e6e'
down_revision: Union[str, Sequence[str], None] = '674238eac5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_connections', sa.Column('facebook_page_id', sa.String(), nullable=True))
    op.add_column('social_connections', sa.Column('facebook_page_name', sa.String(), nullable=True))
    op.add_column('social_connections', sa.Column('facebook_page_access_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_connections', 'facebook_page_access_token')
    op.drop_column('social_connections', 'facebook_page_name')
    op.drop_column('social_connections', 'facebook_page_id')
    # ### end Alembic commands ###
