"""Add new column to User table

Revision ID: a1f2ddd9f649
Revises: 20ac8f0c2587
Create Date: 2025-10-25 15:45:17.367168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f2ddd9f649'
down_revision: Union[str, Sequence[str], None] = '20ac8f0c2587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('video_urls', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('platform_specific_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'platform_specific_content')
    op.drop_column('posts', 'video_urls')
    # ### end Alembic commands ###
