"""add_facebook_page_fields

Revision ID: a201e722015a
Revises: 89c1b0505e6e
Create Date: 2026-01-02 09:08:39.253386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a201e722015a'
down_revision: Union[str, Sequence[str], None] = '89c1b0505e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_connections', sa.Column('facebook_page_category', sa.String(), nullable=True))
    op.add_column('social_connections', sa.Column('facebook_page_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_connections', 'facebook_page_picture')
    op.drop_column('social_connections', 'facebook_page_category')
    # ### end Alembic commands ###
