"""added_protocol_and_secret_auth_token

Revision ID: ae6a2f038468
Revises: a201e722015a
Create Date: 2026-01-07 10:25:11.978237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6a2f038468'
down_revision: Union[str, Sequence[str], None] = 'a201e722015a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_connections', sa.Column('protocol', sa.String(), nullable=True))
    op.add_column('social_connections', sa.Column('oauth_token_secret', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_connections', 'oauth_token_secret')
    op.drop_column('social_connections', 'protocol')
    # ### end Alembic commands ###
